
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ATRIBUTO_HREF ATRIBUTO_SRC ETIQUETA_APERTURA ETIQUETA_CIERREdocumento : bloque_elementosbloque_elementos : elemento bloque_elementos\n| vacioelemento : ETIQUETA_APERTURA\n| ETIQUETA_CIERRE\n| ATRIBUTO_HREF\n| ATRIBUTO_SRCvacio :'
    
_lr_action_items = {'ETIQUETA_APERTURA':([0,3,5,6,7,8,],[5,5,-4,-5,-6,-7,]),'ETIQUETA_CIERRE':([0,3,5,6,7,8,],[6,6,-4,-5,-6,-7,]),'ATRIBUTO_HREF':([0,3,5,6,7,8,],[7,7,-4,-5,-6,-7,]),'ATRIBUTO_SRC':([0,3,5,6,7,8,],[8,8,-4,-5,-6,-7,]),'$end':([0,1,2,3,4,5,6,7,8,9,],[-8,0,-1,-8,-3,-4,-5,-6,-7,-2,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'documento':([0,],[1,]),'bloque_elementos':([0,3,],[2,9,]),'elemento':([0,3,],[3,3,]),'vacio':([0,3,],[4,4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> documento","S'",1,None,None,None),
  ('documento -> bloque_elementos','documento',1,'p_documento','parser.py',29),
  ('bloque_elementos -> elemento bloque_elementos','bloque_elementos',2,'p_bloque_elementos','parser.py',33),
  ('bloque_elementos -> vacio','bloque_elementos',1,'p_bloque_elementos','parser.py',34),
  ('elemento -> ETIQUETA_APERTURA','elemento',1,'p_elemento','parser.py',38),
  ('elemento -> ETIQUETA_CIERRE','elemento',1,'p_elemento','parser.py',39),
  ('elemento -> ATRIBUTO_HREF','elemento',1,'p_elemento','parser.py',40),
  ('elemento -> ATRIBUTO_SRC','elemento',1,'p_elemento','parser.py',41),
  ('vacio -> <empty>','vacio',0,'p_vacio','parser.py',45),
]
